name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git Large File Storage (LFS)
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt-get install git-lfs
        git lfs install

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git remote add hf https://huggingface.co/spaces/soutrik/EraV2_S20_Tokenization
        git push hf main
